version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-colally}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-colally}
      POSTGRES_DB: ${POSTGRES_DB:-colally_db}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  postgres-data:
  mongo-data:
